In [143]:
import pandas as pd
import plotnine as p9

In [144]:
csv_file_url = "https://raw.githubusercontent.com/owid/notebooks/main/JoeHasell/Povcal_data_work/Poverty_and_inequality_measures_from_PovCal_2021.csv"

In [145]:
df = pd.read_csv('https://raw.githubusercontent.com/owid/notebooks/main/JoeHasell/Povcal_data_work/Poverty_and_inequality_measures_from_PovCal_2021.csv')

In [146]:
df.head()

,Entity,Year,$1.90 per day - share of population below poverty line,$1.90 per day - poverty gap index,$1.90 per day - total number of people below poverty line,$1.90 per day - absolute poverty gap,$3.20 per day - share of population below poverty line,$3.20 per day - poverty gap index,$3.20 per day - total number of people below poverty line,$3.20 per day - absolute poverty gap,...,Decile 5 – average income or consumption,Decile 6 – average income or consumption,Decile 7 – average income or consumption,Decile 8 – average income or consumption,Decile 9 – average income or consumption,Decile 10 – average income or consumption,$1.00 per day - share of population below poverty line,$1.00 per day - poverty gap index,$1.00 per day - total number of people below poverty line,$1.00 per day - absolute poverty gap
0,Albania,1981,0.464528,0.000846,12663.29,4.622100,7.623522,0.013227,207821.48,75.854840,...,6.082442,6.790125,7.853463,9.051080,10.814843,15.402078,0.057416,0.000069,1565.19,0.571293
1,Albania,1982,0.407918,0.000816,11357.58,4.145518,7.410390,0.012735,206325.86,75.308938,...,6.130848,6.844163,7.915964,9.123112,10.900912,15.524654,0.057416,0.000065,1598.62,0.583495
2,Albania,1983,0.464528,0.000854,13210.98,4.822009,7.623522,0.013371,216809.92,79.135619,...,6.068509,6.774571,7.835474,9.030348,10.790071,15.366798,0.057416,0.000071,1632.88,0.596002
3,Albania,1984,0.534846,0.000987,15534.22,5.669991,8.790304,0.015602,255308.14,93.187471,...,5.867792,6.550500,7.576313,8.731666,10.433186,14.858537,0.057416,0.000087,1667.60,0.608675
4,Albania,1985,0.534846,0.001000,15856.91,5.787773,8.855139,0.015814,262533.80,95.824836,...,5.850741,6.531465,7.554298,8.706293,10.402868,14.815360,0.057416,0.000089,1702.24,0.621318

In [147]:
#df.Entity.unique().tolist()

In [148]:
# Check population – note that Suriname has population less than one (one person...)

df.loc[df.Population < 1][["Entity", "Year", "Population"]]

        Entity  Year  Population
5820  Suriname  1981    0.360143
5821  Suriname  1982    0.360920
5822  Suriname  1983    0.362276
5823  Suriname  1984    0.364733
5824  Suriname  1985    0.368638
5825  Suriname  1986    0.374140
5826  Suriname  1987    0.381037
5827  Suriname  1988    0.388881
5828  Suriname  1989    0.397085
5829  Suriname  1990    0.405168
5830  Suriname  1991    0.413005
5831  Suriname  1992    0.420655
5832  Suriname  1993    0.428030
5833  Suriname  1994    0.435105
5834  Suriname  1995    0.441851
5835  Suriname  1996    0.448213
5836  Suriname  1997    0.454161
5837  Suriname  1998    0.459831
5838  Suriname  1999    0.465385
5839  Suriname  2000    0.470949
5840  Suriname  2001    0.476579
5841  Suriname  2002    0.482235
5842  Suriname  2003    0.487942
5843  Suriname  2004    0.493679
5844  Suriname  2005    0.499464
5845  Suriname  2006    0.505295
5846  Suriname  2007    0.511181
5847  Suriname  2008    0.517123
5848  Suriname  2009    0.523111
5849  Suriname  2010    0.529131
5850  Suriname  2011    0.535179
5851  Suriname  2012    0.541245
5852  Suriname  2013    0.547291
5853  Suriname  2014    0.553273
5854  Suriname  2015    0.559143
5855  Suriname  2016    0.564888
5856  Suriname  2017    0.570496
5857  Suriname  2018    0.575991

In [149]:
# -> drop weird population figures....
df = df.loc[df.Population > 1]

In [150]:
df_2017 = df.loc[df.Year == 2017]

In [151]:
df_2017.head()

,Entity,Year,$1.90 per day - share of population below poverty line,$1.90 per day - poverty gap index,$1.90 per day - total number of people below poverty line,$1.90 per day - absolute poverty gap,$3.20 per day - share of population below poverty line,$3.20 per day - poverty gap index,$3.20 per day - total number of people below poverty line,$3.20 per day - absolute poverty gap,...,Decile 5 – average income or consumption,Decile 6 – average income or consumption,Decile 7 – average income or consumption,Decile 8 – average income or consumption,Decile 9 – average income or consumption,Decile 10 – average income or consumption,$1.00 per day - share of population below poverty line,$1.00 per day - poverty gap index,$1.00 per day - total number of people below poverty line,$1.00 per day - absolute poverty gap
36,Albania,2017,1.266547,0.001935,36393.68,13.283694,8.189585,0.017827,235324.20,85.893334,...,6.545282,7.666863,9.089712,10.931756,13.746468,21.321229,0.000000,0.000000,0.00,0.000000
75,Algeria,2017,0.329316,0.001254,136301.21,49.749942,2.323713,0.004917,961766.17,351.044654,...,7.500135,8.404083,9.458235,10.832820,13.072209,20.809938,0.090970,0.000729,37651.93,13.742953
114,Angola,2017,45.069260,0.195752,13438187.68,4904.938503,68.034330,0.350932,20285624.73,7404.253026,...,NaN,NaN,NaN,NaN,NaN,NaN,20.254290,0.069902,6039170.61,2204.297272
153,Argentina (Urban),2017,0.928490,0.002923,375209.23,136.951368,3.181663,0.009948,1285731.46,469.291984,...,14.480729,17.686371,21.531053,26.668433,34.959245,62.024468,0.206965,0.001507,83635.91,30.527108
192,Armenia,2017,0.880793,0.001405,25937.68,9.467252,8.096853,0.016339,238436.86,87.029452,...,5.745936,6.507594,7.401714,8.725566,10.804916,21.848572,0.024049,0.000021,708.18,0.258487

In [152]:
exclude_list = ['China (Rural)','China (Urban)','East Asia and Pacific','Europe and Central Asia','India (Rural)','India (Urban)','Indonesia (Rural)','Indonesia (Urban)','Latin America and the Caribbean','Middle East and North Africa','Other high Income (World Bank)','South Asia','Sub-Saharan Africa','Suriname (Urban)','World']

In [153]:
# Check population

In [154]:
df_2017_countries = df_2017[~df_2017["Entity"].isin(exclude_list)]

In [155]:
df_2017_countries.head()

,Entity,Year,$1.90 per day - share of population below poverty line,$1.90 per day - poverty gap index,$1.90 per day - total number of people below poverty line,$1.90 per day - absolute poverty gap,$3.20 per day - share of population below poverty line,$3.20 per day - poverty gap index,$3.20 per day - total number of people below poverty line,$3.20 per day - absolute poverty gap,...,Decile 5 – average income or consumption,Decile 6 – average income or consumption,Decile 7 – average income or consumption,Decile 8 – average income or consumption,Decile 9 – average income or consumption,Decile 10 – average income or consumption,$1.00 per day - share of population below poverty line,$1.00 per day - poverty gap index,$1.00 per day - total number of people below poverty line,$1.00 per day - absolute poverty gap
36,Albania,2017,1.266547,0.001935,36393.68,13.283694,8.189585,0.017827,235324.20,85.893334,...,6.545282,7.666863,9.089712,10.931756,13.746468,21.321229,0.000000,0.000000,0.00,0.000000
75,Algeria,2017,0.329316,0.001254,136301.21,49.749942,2.323713,0.004917,961766.17,351.044654,...,7.500135,8.404083,9.458235,10.832820,13.072209,20.809938,0.090970,0.000729,37651.93,13.742953
114,Angola,2017,45.069260,0.195752,13438187.68,4904.938503,68.034330,0.350932,20285624.73,7404.253026,...,NaN,NaN,NaN,NaN,NaN,NaN,20.254290,0.069902,6039170.61,2204.297272
153,Argentina (Urban),2017,0.928490,0.002923,375209.23,136.951368,3.181663,0.009948,1285731.46,469.291984,...,14.480729,17.686371,21.531053,26.668433,34.959245,62.024468,0.206965,0.001507,83635.91,30.527108
192,Armenia,2017,0.880793,0.001405,25937.68,9.467252,8.096853,0.016339,238436.86,87.029452,...,5.745936,6.507594,7.401714,8.725566,10.804916,21.848572,0.024049,0.000021,708.18,0.258487

In [156]:
df_2017_countries["threshold Above $30 per day"] = df_2017_countries["Population"] - df_2017_countries["$30.00 per day - total number of people below poverty line"]

/var/folders/x7/v_yg2r8j0q19373df27vt6nm0000gp/T/ipykernel_84697/2903881341.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [157]:
df_2017_countries["threshold $10 - $30 per day"] = df_2017_countries["$30.00 per day - total number of people below poverty line"] - df_2017_countries["$10.00 per day - total number of people below poverty line"]

/var/folders/x7/v_yg2r8j0q19373df27vt6nm0000gp/T/ipykernel_84697/3912326866.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [158]:
df_2017_countries["threshold $1.90 - $10 per day"] = df_2017_countries["$10.00 per day - total number of people below poverty line"] - df_2017_countries["$1.90 per day - total number of people below poverty line"]

/var/folders/x7/v_yg2r8j0q19373df27vt6nm0000gp/T/ipykernel_84697/1327207698.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [159]:
df_2017_countries["threshold below $1.90 per day"] = df_2017_countries["$1.90 per day - total number of people below poverty line"]

/var/folders/x7/v_yg2r8j0q19373df27vt6nm0000gp/T/ipykernel_84697/2142158082.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [160]:
# Calc shares

df_2017_countries["share below $1.90 per day"] = df_2017_countries["threshold below $1.90 per day"]/df_2017_countries["Population"]
df_2017_countries["share $1.90 - $10 per day"] = df_2017_countries["threshold $1.90 - $10 per day"]/df_2017_countries["Population"]
df_2017_countries["share $10 - $30 per day"] = df_2017_countries["threshold $10 - $30 per day"]/df_2017_countries["Population"]
df_2017_countries["share Above $30 per day"] = df_2017_countries["threshold Above $30 per day"]/df_2017_countries["Population"]
df_2017_countries.head(n=20)

/var/folders/x7/v_yg2r8j0q19373df27vt6nm0000gp/T/ipykernel_84697/1268183930.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/var/folders/x7/v_yg2r8j0q19373df27vt6nm0000gp/T/ipykernel_84697/1268183930.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/var/folders/x7/v_yg2r8j0q19373df27vt6nm0000gp/T/ipykernel_84697/1268183930.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/var/folders/x7/v_yg2r8j0q19373df27vt6nm0000gp/T/ipykernel_84697/1268183930.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,Entity,Year,$1.90 per day - share of population below poverty line,$1.90 per day - poverty gap index,$1.90 per day - total number of people below poverty line,$1.90 per day - absolute poverty gap,$3.20 per day - share of population below poverty line,$3.20 per day - poverty gap index,$3.20 per day - total number of people below poverty line,$3.20 per day - absolute poverty gap,...,$1.00 per day - total number of people below poverty line,$1.00 per day - absolute poverty gap,threshold Above $30 per day,threshold $10 - $30 per day,threshold $1.90 - $10 per day,threshold below $1.90 per day,share below $1.90 per day,share $1.90 - $10 per day,share $10 - $30 per day,share Above $30 per day
36,Albania,2017,1.266547,0.001935,36393.68,13.283694,8.189585,0.017827,235324.20,85.893334,...,0.00,0.000000,22477.62,824128.15,1.990458e+06,36393.68,0.012665,0.692705,0.286807,0.007823
75,Algeria,2017,0.329316,0.001254,136301.21,49.749942,2.323713,0.004917,961766.17,351.044654,...,37651.93,13.742953,404426.27,12431998.90,2.841647e+07,136301.21,0.003293,0.686567,0.300368,0.009771
114,Angola,2017,45.069260,0.195752,13438187.68,4904.938503,68.034330,0.350932,20285624.73,7404.253026,...,6039170.61,2204.297272,109144.21,1022416.28,1.524700e+07,13438187.68,0.450693,0.511357,0.034290,0.003661
153,Argentina (Urban),2017,0.928490,0.002923,375209.23,136.951368,3.181663,0.009948,1285731.46,469.291984,...,83635.91,30.527108,8148359.81,20856373.17,1.103073e+07,375209.23,0.009285,0.272966,0.516111,0.201639
192,Armenia,2017,0.880793,0.001405,25937.68,9.467252,8.096853,0.016339,238436.86,87.029452,...,708.18,0.258487,35436.65,493307.93,2.390127e+06,25937.68,0.008808,0.811641,0.167518,0.012034
231,Australia,2017,0.498484,0.003699,122636.29,44.762245,0.744415,0.004319,183139.91,66.846068,...,122636.29,44.762245,19930544.93,4307653.33,2.410255e+05,122636.29,0.004985,0.009797,0.175095,0.810124
270,Austria,2017,0.318090,0.002383,27984.14,10.214212,0.398292,0.002927,35040.04,12.789613,...,20406.03,7.448202,7285162.35,1401958.39,8.246112e+04,27984.14,0.003181,0.009373,0.159358,0.828088
309,Azerbaijan,2017,0.000000,0.000000,0.00,0.000000,0.000000,0.000000,0.00,0.000000,...,0.00,0.000000,1187470.10,8237187.11,4.293758e+05,0.00,0.000000,0.043574,0.835920,0.120506
348,Bangladesh,2017,11.351680,0.019758,18125294.77,6615.732592,47.488390,0.131215,75824993.92,27676.122780,...,540567.19,197.307023,333376.23,5511493.56,1.357004e+08,18125294.77,0.113517,0.849877,0.034518,0.002088
387,Belarus,2017,0.000000,0.000000,0.00,0.000000,0.027522,0.000024,2614.08,0.954137,...,0.00,0.000000,934258.75,7471963.24,1.092042e+06,0.00,0.000000,0.114973,0.786666,0.098361
426,Belgium,2017,0.147869,0.001174,16820.29,6.139405,0.226124,0.001499,25721.97,9.388520,...,16820.29,6.139405,9017658.78,2280312.70,6.036623e+04,16820.29,0.001479,0.005307,0.200464,0.792750
465,Belize,2017,13.661150,0.058233,51334.37,18.737044,25.964520,0.112990,97566.62,35.611815,...,21440.67,7.825846,18343.99,76480.26,2.296104e+05,51334.37,0.136612,0.611041,0.203530,0.048817
504,Benin,2017,47.728800,0.215264,5333790.77,1946.833630,74.705410,0.383557,8348481.97,3047.195918,...,2256131.76,823.488093,14601.52,377624.67,5.449187e+06,5333790.77,0.477288,0.487614,0.033791,0.001307
543,Bhutan,2017,1.542608,0.002447,11501.19,4.197935,12.150660,0.025888,90591.43,33.065873,...,205.17,0.074889,8909.16,207245.69,5.179120e+05,11501.19,0.015426,0.694654,0.277970,0.011949
582,Bolivia,2017,6.546306,0.028758,732718.47,267.442243,12.417260,0.054595,1389845.78,507.293711,...,347896.40,126.982186,909480.95,4587618.43,4.963036e+06,732718.47,0.065463,0.443411,0.409870,0.081256
621,Bosnia and Herzegovina,2017,0.058987,0.000141,1976.95,0.721586,0.312642,0.000648,10478.29,3.824575,...,0.00,0.000000,723045.70,2159348.29,4.671561e+05,1976.95,0.000590,0.139386,0.644288,0.215736
660,Botswana,2017,13.984740,0.037673,308381.42,112.559217,35.741900,0.126019,788154.64,287.676445,...,45737.16,16.694062,74176.76,418124.46,1.404445e+06,308381.42,0.139847,0.636900,0.189615,0.033638
699,Brazil,2017,4.418437,0.016366,9183006.89,3351.797514,9.072437,0.036781,18855593.38,6882.291584,...,2747687.95,1002.906100,33328503.32,88290284.63,7.703204e+07,9183006.89,0.044184,0.370642,0.424812,0.160361
738,Bulgaria,2017,1.371766,0.004479,97065.44,35.428884,3.345090,0.011754,236696.80,86.394330,...,30521.45,11.140328,1040377.20,4381220.47,1.557284e+06,97065.44,0.013718,0.220081,0.619171,0.147030
777,Burkina Faso,2017,38.426980,0.090452,7375399.40,2692.020782,73.285740,0.292991,14065940.21,5134.068177,...,625109.52,228.164975,17696.21,397381.59,1.140281e+07,7375399.40,0.384270,0.594104,0.020704,0.000922

In [161]:
df_2017_countries = df_2017_countries[['Entity',\
                                       'threshold below $1.90 per day',\
                                     "threshold $1.90 - $10 per day",\
                                       "threshold $10 - $30 per day",\
                                       "threshold Above $30 per day",\
                                      "share below $1.90 per day",\
                                      "share $1.90 - $10 per day",\
                                      "share $10 - $30 per day",\
                                      "share Above $30 per day",
                                      "Population"]]

In [162]:
df_2017_countries.head()

,Entity,threshold below $1.90 per day,threshold $1.90 - $10 per day,threshold $10 - $30 per day,threshold Above $30 per day,share below $1.90 per day,share $1.90 - $10 per day,share $10 - $30 per day,share Above $30 per day,Population
36,Albania,36393.68,1990457.55,824128.15,22477.62,0.012665,0.692705,0.286807,0.007823,2873457.0
75,Algeria,136301.21,28416471.62,12431998.90,404426.27,0.003293,0.686567,0.300368,0.009771,41389198.0
114,Angola,13438187.68,15246999.83,1022416.28,109144.21,0.450693,0.511357,0.034290,0.003661,29816748.0
153,Argentina (Urban),375209.23,11030731.79,20856373.17,8148359.81,0.009285,0.272966,0.516111,0.201639,40410674.0
192,Armenia,25937.68,2390126.74,493307.93,35436.65,0.008808,0.811641,0.167518,0.012034,2944809.0

In [163]:
df_2017_countries = df_2017_countries.sort_values(by=['share Above $30 per day'])
df_2017_countries["cum_pop"] = df_2017_countries.Population.cumsum()

df_2017_countries.head()

,Entity,threshold below $1.90 per day,threshold $1.90 - $10 per day,threshold $10 - $30 per day,threshold Above $30 per day,share below $1.90 per day,share $1.90 - $10 per day,share $10 - $30 per day,share Above $30 per day,Population,cum_pop
2415,Guinea-Bissau,1173883.81,592097.73,62164.46,0.00,0.642117,0.323879,0.034004,0.000000,1828146.0,1828146.0
3839,Mali,8252743.79,10122569.63,137054.66,25.92,0.445796,0.546800,0.007403,0.000001,18512394.0,20340540.0
5532,Somalia,10010433.42,4525268.98,52544.17,872.43,0.686157,0.310181,0.003602,0.000060,14589119.0,34929659.0
3683,Madagascar,19896905.11,5539934.21,132133.21,1567.47,0.778118,0.216653,0.005167,0.000061,25570540.0,60500199.0
816,Burundi,8475545.97,2314525.40,35220.31,1732.32,0.782814,0.213773,0.003253,0.000160,10827024.0,71327223.0

In [164]:
df_2017_countries.to_csv("povcal_number_at_different_thresholds_2007.csv")

In [165]:
df_2017_countries_long = df_2017_countries[['Entity',\
                                       'threshold below $1.90 per day',\
                                     "threshold $1.90 - $10 per day",\
                                       "threshold $10 - $30 per day",\
                                       "threshold Above $30 per day",]]

df_2017_countries_long = pd.melt(df_2017_countries,id_vars=['Entity'],var_name='metric', value_name='value')

In [166]:
df_2017_countries_long.to_csv("long_povcal_number_at_different_thresholds_2007.csv")